<?php

/*********************************************************************
* Extension configuration file for ext "devlog".
*
* Generated by ext 22-03-2014 21:38 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Developer Log',
  'description' => 'The Developer log extension provides development logging/debugging functionality for usage of t3lib_div::devlog() and a BE module to browse the logs.',
  'category' => 'misc',
  'shy' => 0,
  'dependencies' => 'cms',
  'conflicts' => '',
  'priority' => '',
  'loadOrder' => '',
  'module' => 'mod1',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 1,
  'lockType' => '',
  'author' => 'Rene Fritz, Francois Suter',
  'author_email' => 'typo3@cobweb.ch',
  'author_company' => '',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'version' => '2.11.0',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '4.5.0-6.2.99',
      'cms' => '',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  '_md5_values_when_last_written' => 'a:21:{s:9:"ChangeLog";s:4:"fac9";s:19:"class.tx_devlog.php";s:4:"9182";s:28:"class.tx_devlog_tceforms.php";s:4:"8935";s:21:"ext_conf_template.txt";s:4:"af5a";s:12:"ext_icon.gif";s:4:"cd8e";s:17:"ext_localconf.php";s:4:"a7f0";s:14:"ext_tables.php";s:4:"4845";s:14:"ext_tables.sql";s:4:"8608";s:18:"icon_tx_devlog.gif";s:4:"cd8e";s:13:"locallang.xml";s:4:"68e6";s:26:"locallang_csh_txdevlog.xml";s:4:"b9da";s:16:"locallang_db.xml";s:4:"03db";s:7:"tca.php";s:4:"162e";s:14:"doc/manual.sxw";s:4:"6ba1";s:14:"mod1/clear.gif";s:4:"cc11";s:13:"mod1/conf.php";s:4:"4129";s:14:"mod1/index.php";s:4:"6066";s:18:"mod1/locallang.xml";s:4:"68d2";s:22:"mod1/locallang_mod.xml";s:4:"5454";s:19:"mod1/moduleicon.gif";s:4:"cd8e";s:22:"res/csh_severities.png";s:4:"facf";}',
  'suggests' => 
  array (
  ),
  'comment' => 'Ensured compatibility with TYPO3 CMS 6.2. Added CSRF protection to BE module.',
  'user' => 'francois',
);

?>